version: '3.9'

services:
  django:
    image: stream:0.0.1
    build: .
    ports: 
      - "8000:8000"
    volumes:
      - db-volume:/app/data

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  celery-worker:
    build: .
    command: celery -A stream_video.celery worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - db-volume:/app/data
  celery-beat:
    build: .
    command: celery -A stream_video.celery beat --loglevel=info
    depends_on:
      - redis
    volumes:
      - db-volume:/app/data

volumes:
  db-volume: 
  