version: '3.9'

services:
  # Django service
  django:
    image: stream:0.0.1
    build: .
    ports: 
      - "8000:8000"
  
  # Redis service
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  # Celery worker service
  celery-worker:
    build: .
    command: celery -A stream_video.celery worker --loglevel=info
    depends_on:
      - redis

  # Celery Beat service
  celery-beat:
    build: .
    command: celery -A stream_video.celery beat --loglevel=info
    depends_on:
      - redis