version: '3.9'

services:
  django:
    image: stream:0.0.1
    build: .
    ports:
      - "8000:8000"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  celery-worker:
    build: .
    command: celery -A stream_video.celery worker --loglevel=info
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A stream_video.celery beat --loglevel=info
    depends_on:
      - redis

volumes:
  postgres_data:
