# Generated by Django 4.2.3 on 2023-08-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shortName', models.CharField(blank=True, max_length=255)),
                ('iconUri', models.URLField()),
                ('manifestUri', models.URLField()),
                ('source', models.CharField(max_length=255)),
                ('focus', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('extraText', models.JSONField(default=list)),
                ('certificateUri', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('isFeatured', models.BooleanField(default=False)),
                ('drm', models.JSONField(default=list)),
                ('features', models.JSONField(default=list)),
                ('licenseServers', models.JSONField(default=dict)),
                ('licenseRequestHeaders', models.JSONField(default=dict)),
                ('requestFilter', models.TextField(blank=True, null=True)),
                ('responseFilter', models.TextField(blank=True, null=True)),
                ('clearKeys', models.JSONField(default=dict)),
                ('extraConfig', models.JSONField(blank=True, null=True)),
                ('adTagUri', models.URLField(blank=True, null=True)),
                ('imaVideoId', models.CharField(blank=True, max_length=255, null=True)),
                ('imaAssetKey', models.CharField(blank=True, max_length=255, null=True)),
                ('imaContentSrcId', models.CharField(blank=True, max_length=255, null=True)),
                ('mimeType', models.CharField(blank=True, max_length=255, null=True)),
                ('mediaPlaylistFullMimeType', models.CharField(blank=True, max_length=255, null=True)),
                ('storedProgress', models.FloatField(default=1)),
                ('storedContent', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
