# Generated by Django 4.2.3 on 2023-08-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='clearKeys',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='video',
            name='drm',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='video',
            name='extraText',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='video',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='video',
            name='licenseRequestHeaders',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='video',
            name='licenseServers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
