# Generated by Django 4.2.3 on 2023-08-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_manager', '0002_alter_video_clearkeys_alter_video_drm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='clearKeys',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='video',
            name='drm',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='video',
            name='extraText',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='video',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='video',
            name='licenseRequestHeaders',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='video',
            name='licenseServers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
